const reviews = [
  {
    name: 'Ahmed Raza',
    city: 'Lahore',
    rating: 5,
    text: 'Ordered two watches as gifts. The quality is outstanding for the price. My brother thought I spent 5000+ on it. Will definitely order again!',
    date: '2 weeks ago',
    avatar: 'A',
  },
  {
    name: 'Fatima Malik',
    city: 'Karachi',
    rating: 5,
    text: 'Delivered in just 3 days to Karachi. The watch looks amazing and the COD option makes it super easy. Highly recommended!',
    date: '1 month ago',
    avatar: 'F',
  },
  {
    name: 'Usman Tariq',
    city: 'Islamabad',
    rating: 5,
    text: "Bought it for my dad's birthday. He absolutely loves it. Premium feel, great packaging, and fast delivery. 10/10.",
    date: '3 weeks ago',
    avatar: 'U',
  },
  {
    name: 'Sana Javed',
    city: 'Faisalabad',
    rating: 5,
    text: 'I was skeptical at first but the watch exceeded my expectations. Cash on delivery means no risk. Very happy with my purchase!',
    date: '5 days ago',
    avatar: 'S',
  },
  {
    name: 'Bilal Hassan',
    city: 'Multan',
    rating: 5,
    text: "Best value watch I've seen in Pakistan at this price. The gold accents look stunning. Friends keep asking where I got it from.",
    date: '2 months ago',
    avatar: 'B',
  },
  {
    name: 'Zara Niazi',
    city: 'Rawalpindi',
    rating: 5,
    text: 'Third purchase from Royal Time. Every single watch has been perfect. Delivery is always on time. Trusted seller!',
    date: '1 week ago',
    avatar: 'Z',
  },
];
